#!/usr/bin/env bash
# Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i '/# Add/a\\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/getsalma.tech\/;\n\t}' /etc/nginx/sites-available/default
sudo sh -c 'echo "Ceci n'"'"'est pas une page" > /var/www/html/404.html'
sudo sed -i '/# Add/a\\terror_page 404 /404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/# Add/a\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
